version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm ci
      - run:
          name: npm test
          command: $(npm bin)/nyc npm test && $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls
      - run: npm run lint
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - aws-cli/setup
      - run: npm ci
      - run:
          name: install serverless
          command: 'sudo npm install -g serverless'
      - deploy:
          name: sls deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "main" ]; then
                sls deploy --stage prod --verbose
              else
                sls deploy --stage dev --verbose
              fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          context: aws-serverless
