version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - run: npm ci
      - run:
          name: npm test
          command: $(npm bin)/nyc npm test && $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls
      - run: npm run lint
      - run:
          name: install serverless
          command: 'sudo npm install -g serverless'
      - deploy:
          name: sls deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                sls deploy --stage prod --verbose
              else
                sls deploy --stage dev --verbose
              fi

  vul-check:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - run: npm ci
      - run: npm audit

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "15 16 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vul-check
